import io

path = r"D:\sandbox\extract_csdn_wechat_article_0815_fix\wechat_extractor.py"
raw = io.open(path, "rb").read().decode("utf-8")

old = (
    "    def _normalize_code_blocks(content_node) -> None:\r\n"
    "        \"\"\"Rewrite WeChat code blocks into plain <pre><code> so line numbers and\r\n"
    "        decoration spans do not leak into the Markdown code fence.\"\"\"\r\n"
    "\r\n"
    "        for pre in content_node.find_all(\"pre\"):\r\n"
    "            code = pre.find(\"code\")\r\n"
    "            if code is None:\r\n"
    "                continue\r\n"
    "            for child in list(pre.children):\r\n"
    "                if getattr(child, \"name\", None) == \"section\" and child is not code:\r\n"
    "                    child.decompose()\r\n"
    "            for column in code.find_all(style=re.compile(r\"user-select:\\s*none\")):\r\n"
    "                column.decompose()\r\n"
    "            for empty_span in code.find_all(\"span\", attrs={\"leaf\": \"\"}):\r\n"
    "                if not empty_span.get_text(strip=True) and empty_span.find(\"br\"):\r\n"
    "                    empty_span.decompose()\r\n"
    "\r\n"
    "            leaf_spans = [\r\n"
    "                span\r\n"
    "                for span in code.find_all(\"span\", attrs={\"leaf\": \"\"})\r\n"
    "                if span.get_text(strip=True)\r\n"
    "            ]\r\n"
    "            if leaf_spans:\r\n"
    "                text = \"\\n\".join(span.get_text() for span in leaf_spans)\r\n"
    "            else:\r\n"
    "                text = code.get_text(\"\\n\")\r\n"
)
new = (
    "    def _normalize_code_blocks(content_node) -> None:\r\n"
    "        \"\"\"Rewrite WeChat code blocks into plain <pre><code> so line numbers and\r\n"
    "        decoration spans do not leak into the Markdown code fence.\r\n"
    "\r\n"
    "        \u65b0\u7248\u5fae\u4fe1\u7f16\u8f91\u5668\u628a\u4e00\u884c\u4ee3\u7801\u62c6\u6210\u591a\u4e2a\u9ad8\u4eae token span\uff08leaf\r\n"
    "        \u6216\u88ab\u5f69\u8272 span \u5305\u88f9\u7684 leaf\uff09\uff0c\u884c\u5c3e\u7528 <span leaf=\"\"><br/></span>\r\n"
    "        \u6807\u8bb0\uff1b\u65e7\u7248\u6bcf\u884c\u662f\u4e00\u4e2a\u5b8c\u6574\u7684 leaf span\u3002\u4e0d\u80fd\u7528\r\n"
    "        find_all(attrs={\"leaf\": \"\"})\uff1aBeautifulSoup \u4f1a\u628a\u6ca1\u6709 leaf \u5c5e\u6027\u7684\r\n"
    "        \u5f69\u8272\u5305\u88f9 span \u4e5f\u5339\u914d\u8fdb\u6765\uff0c\u5bfc\u81f4\u6bcf\u4e2a token \u6587\u672c\u91cd\u590d\u3002\"\"\"\r\n"
    "\r\n"
    "        for pre in content_node.find_all(\"pre\"):\r\n"
    "            code = pre.find(\"code\")\r\n"
    "            if code is None:\r\n"
    "                continue\r\n"
    "            for child in list(pre.children):\r\n"
    "                if getattr(child, \"name\", None) == \"section\" and child is not code:\r\n"
    "                    child.decompose()\r\n"
    "            for column in code.find_all(style=re.compile(r\"user-select:\\s*none\")):\r\n"
    "                column.decompose()\r\n"
    "\r\n"
    "            leaf_spans = [\r\n"
    "                span for span in code.find_all(\"span\") if span.has_attr(\"leaf\")\r\n"
    "            ]\r\n"
    "            if leaf_spans:\r\n"
    "                new_style = any(\r\n"
    "                    span.parent is not None and span.parent.name == \"code\"\r\n"
    "                    for span in leaf_spans\r\n"
    "                )\r\n"
    "                if new_style:\r\n"
    "                    lines = []\r\n"
    "                    current = []\r\n"
    "                    for span in leaf_spans:\r\n"
    "                        span_text = span.get_text()\r\n"
    "                        if span_text:\r\n"
    "                            current.append(span_text)\r\n"
    "                        if span.find(\"br\") is not None:\r\n"
    "                            lines.append(\"\".join(current))\r\n"
    "                            current = []\r\n"
    "                    if current:\r\n"
    "                        lines.append(\"\".join(current))\r\n"
    "                    text = \"\\n\".join(lines)\r\n"
    "                else:\r\n"
    "                    text = \"\\n\".join(\r\n"
    "                        span.get_text() for span in leaf_spans if span.get_text()\r\n"
    "                    )\r\n"
    "            else:\r\n"
    "                text = code.get_text(\"\\n\")\r\n"
)
if old not in raw:
    old = old.replace("\r\n", "\n")
    new = new.replace("\r\n", "\n")
assert old in raw, "normalize_code_blocks block not found"
raw = raw.replace(old, new, 1)
io.open(path, "w", encoding="utf-8", newline="").write(raw)
print("wechat_extractor._normalize_code_blocks patched OK")
